/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2016-08-25 16:56:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<body bgcolor=\"pink\">\r\n");

String s1=request.getParameter("fname");
if(s1==null)
{
s1="";
}

      out.write('\r');
      out.write('\n');

String s2=request.getParameter("lname");
if(s2==null)
{
s2="";
}

      out.write('\r');
      out.write('\n');

String s3=request.getParameter("age");
if(s3==null)
{
s3="";
}

      out.write('\r');
      out.write('\n');

String s4=request.getParameter("username");
if(s4==null)
{
s4="";
}

      out.write('\r');
      out.write('\n');

String errorstatus=(String)request.getAttribute("status");
if(errorstatus==null)
{
	errorstatus="";
}

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"/>\r\n");
      out.write("<font class=\"errorFont\">\r\n");
      out.print(errorstatus );
      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("<script src=\"regvalidate.js\"></script>\r\n");
      out.write("<form action=\"RegServlet\" method=\"get\">\r\n");
      out.write("\t\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\tFirstName:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"text\" name=\"fname\" value=\"");
      out.print(s1);
      out.write("\"><br>\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\tLastName:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"text\" name=\"lname\" value=\"");
      out.print(s2);
      out.write("\"><br>\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\tAge:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"text\" name=\"age\" value=\"");
      out.print(s3);
      out.write("\"><br>\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\tUsername:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"text\" name=\"username\" value=\"");
      out.print(s4);
      out.write("\"><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\tPassword:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"password\" name=\"password\" ><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<font class=\"fieldFont\">\r\n");
      out.write("\t\r\n");
      out.write("\temail:\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<input type=\"text\" name=\"email\" ><br>\r\n");
      out.write("\t<input type=\"submit\" value=\"Registration\" onclick=\"return validateRegistration()\"><br>\r\n");
      out.write("</form>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
