/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2016-09-01 16:48:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <body bgcolor=\"gray\"></body>\r\n");
      out.write("  ");

  String s1=request.getParameter("username"); 
  String s2=request.getParameter("password"); 
  if(s1!=null && s2!=null)
  {
  String sql="select * from reg where uname='"+s1+"'and pwd ='"+s2+"'";
  try
  {
  Class.forName("oracle.jdbc.driver.OracleDriver");
  }
  catch(ClassNotFoundException ex)
  {
  ex.printStackTrace();
  }
  
  Connection con=null;
  Statement stmt=null;
  ResultSet rs=null;
  boolean status=false;
  try
  {
  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","JDBC","GREAT123");
  stmt=con.createStatement();
  rs=stmt.executeQuery(sql);
  status=rs.next();
  }
  catch(SQLException ex)
  {
	  ex.printStackTrace();
  }
  finally
  {
	  try
	  {
		  if(rs!=null)
		  {
			  rs.close();
			  rs=null;
		  }
	 }
	  catch(SQLException ex)
	  {
		  ex.printStackTrace();
	  }
	  try
	  {
		  if(stmt!=null)
		  {
			  stmt.close();
			  stmt=null;
		  }
	 }
	  catch(SQLException ex)
	  {
		  ex.printStackTrace();
	  }
	  try
	  {
		  if(con!=null)
		  {
			  con.close();
			  con=null;
		  }
	  }
	  catch(SQLException ex)
	  {
		  ex.printStackTrace();
	  }
	}
  if(status)
  {

      out.write("\r\n");
      out.write("\t  ");
      if (true) {
        _jspx_page_context.forward("success.jsp");
        return;
      }
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");

  }
  else
  {
	  out.println("login is failed");
  }
  }
  else
  {
	  s1="  ";
  }
  
      out.write("\r\n");
      out.write("  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.method}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</br>\r\n");
      out.write("  <form action=\"\" method=\"post\">\r\n");
      out.write("\t  Username:\r\n");
      out.write("\t  <input type=\"text\" name=\"username\"/><br>\r\n");
      out.write("\t  Password:\r\n");
      out.write("\t  <input type=\"password\" name=\"password\"/><br>\r\n");
      out.write("\t  <input type=\"submit\" value=\"Login\"/><br>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
